#ifndef __ENUM_H__
#define __ENUM_H__

enum OBJ_ENUM{
	OBJ_MAP ,OBJ_EFFECT, OBJ_BULLET, OBJ_MISSILE, OBJ_ADDON, OBJ_SHIELD, //플레이어 관련
	OBJ_MONSTER, OBJ_BOSS, OBJ_ITEM, OBJ_BOOM, OBJ_PLAYER, OBJ_UI,

	OBJ_ENEMYBULLET, OBJ_MAPOBJECT,
	OBJ_END
};

enum BULLIT_TYPE{
	PAWN, BOSS
};

enum UI_VALUE{
	UI_NULL ,UI_SPEEDUP, UI_MISSILE, UI_DOUBLE, UI_LASER, UI_OPTION, UI_SHIELD
};

enum IMG_ENUM{
	IMG_TITLE1,IMG_TITLE2,
	//플레이어 관련
	IMG_PLAYER, IMG_BULLET, IMG_MISSILE, IMG_DBULLET, IMG_LASER, 
	IMG_ADDON, IMG_SHIELD, IMG_MAP, IMG_ITEM, IMG_BOOM,
	//몬스터 관련
	IMG_BIGCORE, IMG_PENCE, IMG_RUGAL, IMG_DE, IMG_DUCKER, IMG_GARUN, IMG_JUMPER, IMG_MINIAN,
	IMG_ENEMY_BULLET, IMG_BIGCORE_MISSILE,
	IMG_UI_BLUE, IMG_UI_ORANGE, IMG_UI_BLUE_NO, IMG_UI_ORNAGE_NO,
	IMG_PLAYER_DEAD, IMG_ENEMY_DEAD, IMG_PENCE_DEAD, IMG_BOSS_DEAD,
	IMG_END
};
#endif // !__ENUM_H__
